
server:
  port: 8123

spring:
  security:
    enabled: true

country-code-list: >
  {"countryList":[{"code":"IN","countryName":"India","countryCode":"+91","imageUrl":"/external/images/india-flag.svg","validation":{"minLength":10,"maxLength":10,"pattern":"^[6-9]\\d{9}$","stripPattern":"[\\s-]"},"errorMessages":{"required":"Mobile number is required","invalid":"Please enter a valid mobile number","invalidLength":"Mobile number must be 10 digits"}},{"code":"PL","countryName":"Poland","countryCode":"+48","imageUrl":"/external/images/poland-flag.svg","validation":{"minLength":9,"maxLength":9,"pattern":"^\\d{9}$","stripPattern":"[\\s-]"},"errorMessages":{"required":"Mobile number is required","invalid":"Please enter a valid mobile number","invalidLength":"Mobile number must be 9 digits"}}]}
